# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.5

env:
  - TOXENV=django18
  - TOXENV=django19
  - TOXENV=django110

matrix:
  include:
    - python: 3.5
      env: TOXENV=quality
    - python: 3.5
      env: TOXENV=docs

cache:
  - pip
  
before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov

# Set password via "travis encrypt --add deploy.password"; for details, see
# https://docs.travis-ci.com/user/deployment/pypi
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  password:
    secure: cZkZ566AKyAzQnVni56RfhD560RLTD0NwnmWfKYJIY/GAZeAy7ss8oiidKDbX4w3n05dQO6r3iqA+A/ucEhaOZrX0aw+i3xDnqbIrtuRCLTLU9TDKBx+TJc30Zjay/bwnvtnkujX2Fuk66+UmBIp0PChAq7xDLrx1vEKLYLrEQMfjjhzHUZy/N 6gHCjCVLKSpVLlV/8l7iyjFhnMtil+T1Li3ABeCpNov/hVx1+QaceNfX9TDkpvQp5jrAmqFWtMVt6k52sC/Pqhry7M+YNwLdq+QigbheUfHK82stmw4FTNOPjQjr7XBxnyT+nEgeeohvziiSd8JEwgiyVT7yj/F4kBGxTXbpgbG60kcgUGAMW9/S+asSHC5Oxj8 cFm7DIxtIK6qZYe8lKVNV8DKz/t5Tunjea+pKcTt+wNz7OEEUOfh1bX4QLMai4FyUfNBI9NpVwHOLh8ofq5EUbfyprbaVCxT0uOqgDtzgv2dUPSrQ7Nmb3m3kk2MnDK3/vmkJlhFbVJlHXH3uRV3oRmsVkoZbwTEC7FlCORZp0qByDv5j1vvF1/VjAdJzilbgcW FMQLcU3ak3Emy86QgF7EJJv0aM14/pdW2OH18QsnWgEK3rvZfrEGxsWbLRoWWEg1omgSThPMZp96l0oHsS7wCvonUSTZCkpYgRiK9dhIai7rdNk=
  on:
    tags: true
    condition: '$TOXENV = quality'
